### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by CastorSmith89** [AmbitiousPilots/LittleNavmapOFMTheme#10]
I extracted release v1.0.10 in LNM but, disabled the airspaces and changes to this map but the view is black at all. Location is germany which should be covered. Checked the forum where some others having the same issue so I guess you are already working on that. 

However, I wanted to add the issue here that others see that it is aware. 

My version is 2.6.17
I copied all files from the release in the \data\maps\earth\ directory.

I checked also version v1.0.09 with same issue. 

If I move the map then I also get a strange graphical experience which resets after zoom in or out.
![image](https://user-images.githubusercontent.com/93674909/141074265-f4ad48bc-c188-4ff9-84f1-8c89a7310a2e.png)

**Comment by AndreGeddert** [comment]
The latest commit #9 ist not included in the last release. If you download latest source it should work.

**Comment by CastorSmith89** [comment]
Thanks. It is working after I changed expiration date of the map to -1 and of course downloaded the latest code instead the release. 

<texture name="map" expire="-1" >
