### ISSUE TITLE
Maps no longer loading

### ISSUE THREAD

**Issue by MedicoreV8** [AmbitiousPilots/LittleNavmapOFMTheme#11]
Hi,

For a few weeks I've had the problem where the maps are no longer loading.
I re-downloaded the latest release, removed the temp files from the appdata folder but no dice.
It looks as if there are no map tiles available anymore.
[https://i.ibb.co/KGLM76j/Capture.png](https://i.ibb.co/KGLM76j/Capture.png)

**Comment by bergziege** [comment]
Same here. Glad I always test my setup 2h prior to a flight ;-)

**Comment by bergziege** [comment]
Quickfix:

At `Little Navmap\data\maps\earth\openflightmaps` find the `openflightmaps.dgml` file and change `2111` on line 28 and 37 to `2113`.

I will create a merge request later this evening-

**Comment by AmbitiousPilots** [comment]
Yes, that's right. The older AIRAC links become invalid after they're outdated. Updating the URL param to the current available AIRAC cycle allows to load the new tiles. Will update the packages. Thanks for reaching out ;)

**Comment by AndreGeddert** [comment]
Oops, seems you were faster than my pull request :-D #12

**Comment by AmbitiousPilots** [comment]
Merged! Enjoy ;)

**Comment by AndreGeddert** [comment]
Thanks. Im just doing this so i can write in my CV "regulary contributing to open source project". Nobody has to know im just incrementing by 1 every time 🤣
