### ISSUE TITLE
Some areas do not repaint at low zoom levels

### ISSUE THREAD

**Issue by jonaseberle** [AmbitiousPilots/LittleNavmapOFMTheme#14]
Thank you so much for this project!
And thanks to openflightmaps. This is a game-changer!

I have an issue: When panning the map at low zoom levels I have areas that are not repainted.

This leads to the map as well as navaids to be "smearing":
![image](https://user-images.githubusercontent.com/1678001/152658619-9f80a91c-8308-4223-a0b9-a45cd0a99a48.png)

For one specific zoom level, the problematic area is reproducibly the same.
For the min zoom level as shown in the image above it is an area south of EDDK until Northern Italy and From the Western border of Paris FIR to EDDM.

To prevent smearing within that area I have to stay at this zoom level:
![image](https://user-images.githubusercontent.com/1678001/152658850-081c38dc-e4d7-4325-aaeb-b68ac2d2a870.png)

Is that just me? Is that an issue with the map tiles or with LittleNavmap?

**Comment by albar965** [comment]
Smearing was a LNM/Marble issue and fixed for the next release.

**Comment by jonaseberle** [comment]
Thanks. Is LittleNavmap using the marble engine? Sorry, I am really impressed by it but haven't checked in the code yet how it works.

**Comment by albar965** [comment]
LNM uses Marble for the background maps. I have a clone of the Marble repo [right here](https://github.com/albar965/marble/tree/lnm/1.1) where I add fixes and adapt it to my needs.
Alex

**Comment by jonaseberle** [comment]
Thank you so much. I just realize that you are the creator of LittleNavmap  :) Together with this it makes VFR flying such a joy.

**Comment by AmbitiousPilots** [comment]
@jonaseberle Glad you enjoy the VFR theme in LittleNavmap.

@albar965 Thanks for the reply. Did you manage to or are you planning to change the "smearing" in marble yet?

**Comment by albar965** [comment]
@AmbitiousPilots It's already fixed in the current Marble branch lnm/1.1. 
The commit is albar965/marble@19e65bd03c78ce3d9f4634cbf9374dbcfdc4b104

**Comment by AmbitiousPilots** [comment]
@albar965 Great! Thanks :)
