### ISSUE TITLE
Preview image 0.jpg has to match tile size

### ISSUE THREAD

**Issue by albar965** [AmbitiousPilots/LittleNavmapOFMTheme#15]
I recently spent an afternoon debugging deep into Marble trying to fix a [crash with Maptiler and MapBox maps](https://www.avsim.com/forums/topic/614851-little-navmap-alphadevelopment-277-released/?tab=comments#comment-4722536) while using the spherical map theme in the LNM alpha release. 

At the end I noticed that the 0.jpg/0.png has to match the 512x512 tile size too to avoid the crash. This could apply to your map theme too since the Jpg is 256x256 and the tiles are 512x512.

Just a hint to avoid potential problems with LNM and your terrific map theme. :upside_down_face: 

Alex

**Comment by AmbitiousPilots** [comment]
Thanks for investigating and sharing your findings! 

I've updated the files accordingly. Looks like it works fine 👍 

Cheers

**Comment by albar965** [comment]
That was quick! Thanks!
