### ISSUE TITLE
Doesn't load tiles since last couple of days

### ISSUE THREAD

**Issue by racer01** [AmbitiousPilots/LittleNavmapOFMTheme#16]
I'm not sure what's wrong, it doesn't load a number of tiles at all sicne a couple of days (like 2-3 week). It's always the same tiles even if I zoom in and out.
![image](https://user-images.githubusercontent.com/14020544/156051430-534ff155-480c-4056-849c-317091d61b57.png)
![image](https://user-images.githubusercontent.com/14020544/156051523-658b9ac7-3be7-42cc-9c26-5e227ce5fd8e.png)
![image](https://user-images.githubusercontent.com/14020544/156051553-1048aba7-7562-4ade-b9e5-628a086a195c.png)

**Comment by AndreGeddert** [comment]
AIRAC 2202 is active. I will create a change. Standby.

**Comment by AndreGeddert** [comment]
Created Pull Request #17

**Comment by racer01** [comment]
I changed the url to 2202 then cleared the lnm caches and it works, thanks!
