### ISSUE TITLE
OFM black tiles everywhere...

### ISSUE THREAD

**Issue by 3DSpotters** [AmbitiousPilots/LittleNavmapOFMTheme#22]
Hi,

I use LNM v2.8.7 for Linux x64 and other maps are OK now (after SSL certificate problem patched) but OFM is blak everywhere...

And yes, I've deleted all the "marble" LFM cache.
https://tinypic.host/i/ofm-black-lnm-2023-01-06-13-39-10.fqL6p

**Comment by 3DSpotters** [comment]
OK, I've changed in file: openflightmaps.dgml
2x: query="path=2205/base/latest
 to ==>
    query="path=2213/base/latest
    
OFM maps WORK NOW ;-)

https://tinypic.host/i/ofm-work-2023-01-06-14-12-22.fqCA9

**Comment by jonaseberle** [comment]
@3DSpotters You can also use this change: https://github.com/AmbitiousPilots/LittleNavmapOFMTheme/pull/20/files (`latest/base/latest`).

@AmbitiousPilots could we get that merged?
