### ISSUE TITLE
CTD when using OpenFlightMap

### ISSUE THREAD

**Issue by CaptainGeorgeIF** [AmbitiousPilots/LittleNavmapOFMTheme#3]
Hello,

I can successfully open Little Navmap, but once I select OpenFlightMaps I get a Crash To Desktop.
Faulting module is libmarblewidget-qt5.dll if that helps.

Thank you.

**Comment by albar965** [comment]
I also get this crash and this happens due to OFM delivering different image sizes. They have to change the image format.

**Comment by AndreGeddert** [comment]
Just tried with latest release. Got the crashes too when zooming.

**Comment by AmbitiousPilots** [comment]
I cannot reproduce the issues you got. Am running the latest version as well, used all available LNM features and zooming. No CTD.

**Comment by AndreGeddert** [comment]
This is the LNM Application Crash i got:
```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2021-02-15T09:34:42.2157529Z" /> 
  <EventRecordID>9711</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>celine.spaceballcity.net</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>littlenavmap.exe</Data> 
  <Data>0.0.0.0</Data> 
  <Data>600d7a00</Data> 
  <Data>libmarblewidget-qt5.dll</Data> 
  <Data>0.0.0.0</Data> 
  <Data>5ed02561</Data> 
  <Data>c0000005</Data> 
  <Data>001d32fa</Data> 
  <Data>51a0</Data> 
  <Data>01d7037db30f774a</Data> 
  <Data>C:\Games\MSFS\Tools\Little Navmap\littlenavmap.exe</Data> 
  <Data>C:\Games\MSFS\Tools\Little Navmap\libmarblewidget-qt5.dll</Data> 
  <Data>1d03df88-d8be-4b1d-bb1f-36677d78cd96</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>

```

**Comment by AmbitiousPilots** [comment]
Yea it's the same error that @CaptainGeorgeIF and @albar965 got as well, namely `libmarblewidget-qt5.dll`, which is the map rendering library. The weird thing is, I'm using this map on a regular basis for VFR flights, but without any crash so far.

**Comment by AndreGeddert** [comment]
Ok, ive deleted the caches and now it crashes right from the start 🤣

**Comment by AmbitiousPilots** [comment]
Will do that now as well and restart, stand by.

**Comment by AndreGeddert** [comment]
ok, after removing the openflightmaps folder it starts again.

**Comment by AmbitiousPilots** [comment]
So, deleted the map cache, restarted LNM. Then it showed me the black tiles due to uncovered area. Moved to EHAM. Loaded the map tiles as usual. 

![screenshot_lnm_vfr_theme](https://user-images.githubusercontent.com/72250898/107934002-c87b8500-6f7f-11eb-939b-ba007c125679.jpg)

**Comment by AmbitiousPilots** [comment]
Should the tile size be the cause of the error (what Albar said), you may open the `openflightmaps.dgml` file with a text editor and look for the two `<tileSize width="512" height="512" />` lines. Change them to `<tileSize width="256" height="256" />`. Save and restart LNM. I think someone tried this before, not sure if that solved the problem.

**Comment by AndreGeddert** [comment]
With tileSize 256 it starts now but gives me really strange scattered tiles like this:
![grafik](https://user-images.githubusercontent.com/6795099/107936678-35444e80-6f83-11eb-9f15-20f5a50b350a.png)

**Comment by AmbitiousPilots** [comment]
Ok, so the tiles are only provided in a 512x512 pixel format. So per tile actually 2 tiles are shown. 

I've just received an answer on the FS forums from someone that had the same issue, and after a fresh install of LNM he got it working fine. He said it must've been a setting in the .ini that prevented the map from working. 

FYI, the config files are stored here:
`C:\Users\[USERNAME]\AppData\Roaming\ABarthel`

IMHO, this is a caching issue that triggers an error in the marble map rendering library.

**Comment by AndreGeddert** [comment]
Ok, after removing the config and clearing the cache it looks good at first glance. No crash so far.
Thank you very much.

**Comment by AndreGeddert** [comment]
Hi, with AIRAC 2105 the pain comes back :)
Its definitely the little_navmap.ini file that causes the CTDs. I swapped a fresh ini with my ini backup forth and back and with the fresh ini it always works. With the backuped ini it works in.. some way. Some tiles load. It seems that when tiles on the home position, where the map is when the application starts, are not cached, it chrashes right from the start, but when some tiles are already cached, with the fresh ini, other tiles are also loaded and cached with the backuped ini.
