### ISSUE TITLE
Map not displaying correctly south of france

### ISSUE THREAD

**Issue by Larryadd** [AmbitiousPilots/LittleNavmapOFMTheme#6]
first of all, thx a lot for this addon !
I have an issue, map is not displaying fine in the south of France, a big part of the alps (switzerland), and north of Italy.
it varies when zooming.

If you have an idea on how to resolve this, I'd be greatfull.

Thanks again.

**Comment by AmbitiousPilots** [comment]
Hi, thanks for reaching out. 

Does it work for you on the website of open flightmaps directly (scroll down to the map)? 

https://www.openflightmaps.org/wp-content/plugins/ofmTileMap/ofmTileMap_full.php?airac=2108&language=local&coverage&controls

Let me know.
